name: Deploy to Arenhost

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ARENHOST

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy on Arenhost server via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ vars.HOST }}
          username: ${{ vars.USERNAME }}
          password: ${{ vars.PASSWORD }}
          script: |
            cd /home/pondoknu/disyfa.cloud/studex-counter
            git restore .
            git pull
            rm -rf vendor
            ../../composer install
            php artisan migrate:fresh
            php artisan db:seed --class GroupSeeder
